project_id = "xvjoigimbjrocxdxasaf"

[functions.populate-libraries]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.analyze-media]
verify_jwt = false

[functions.ai-vision-analysis]
verify_jwt = false

[functions.generate-captions]
verify_jwt = false

[functions.speaker-diarization]
verify_jwt = false

[functions.index-youtube-video]
verify_jwt = false
