project_id = "xvjoigimbjrocxdxasaf"

[functions.populate-libraries]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.analyze-media]
verify_jwt = false
